# ESLint config
# http://eslint.org/

env:
  browser: true
  jquery: true

rules:
  strict: 2

  comma-dangle:
    - 2
    - 'never'

  indent:
    - 2
    - 2

  quotes:
    - 2
    - single

  brace-style:
    - 1
    - '1tbs'

  semi:
    - 2
    - 'always'

  linebreak-style:
    - 2
    - 'unix'

  comma-style:
    - 1
    - 'last'

  curly: 2

  eqeqeq:
    - 2
    - 'allow-null'

  key-spacing:
    - 1
    -
      beforeColon: false
      afterColon: true

  comma-spacing:
    - 1
    -
      before: false
      after: true

  space-before-blocks:
    - 1
    - 'always'

  keyword-spacing:
    - 1
    -
      before: true
      after: true

  space-in-parens:
    - 1
    - 'never'

  space-before-function-paren:
    - 1
    - 'never'

  no-trailing-spaces: 1
