# sass-lint config
# https://github.com/sasstools/sass-lint/tree/master/docs

files:
  include: 'assets/styles/**/*.scss'

options:
  formatter: stylish
  merge-default-rules: false

rules:
  bem-depth:
    - 0

  border-zero:
    - 0

  brace-style:
    - 1
    - style: 1tbs
      allow-single-line: false

  class-name-format:
    - 0

  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false

  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true

  extends-before-declarations:
    - 0

  extends-before-mixins:
    - 0

  final-newline:
    - 1
    - include: true

  force-attribute-nesting:
    - 0

  force-element-nesting:
    - 0

  force-pseudo-nesting:
    - 0

  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: camelcase

  hex-length:
    - 1
    - style: short

  hex-notation:
    - 1
    - style: lowercase

  id-name-format:
    - 1
    - allow-leading-underscore: true
      convention: camelcase

  indentation:
    - 1
    - size: 4

  leading-zero:
    - 1
    - include: false

  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: camelcase

  mixins-before-declarations:
    - 1

  nesting-depth:
    - 0

  no-color-keyword:
    - 1

  no-color-literals:
    - 0

  no-css-comments:
    - 0

  no-debug:
    - 1

  no-duplicate-properties:
    - 0

  no-empty-rulesets:
    - 1

  no-extends:
    - 0

  no-ids:
    - 0

  no-important:
    - 0

  no-invalid-hex:
    - 1

  no-mergeable-selectors:
    - 0

  no-misspelled-properties:
    - 1
    - extra-properties: []

  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: true

  no-trailing-zero:
    - 1

  no-transition-all:
    - 0

  no-url-protocols:
    - 1

  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []

  one-declaration-per-line:
    - 1

  placeholder-in-extend:
    - 1

  placeholder-name-format:
    - 1
    - convention: camelcase

  property-sort-order:
    - 0
    - order: concentric
    - ignore-custom-properties: false

  property-units:
    - 1
    - global:
        - em
        - rem
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - s
        - '%'
      per-property: {}

  quotes:
    - 1
    - style: double

  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3

  single-line-per-selector:
    - 1

  space-after-bang:
    - 1
    - include: false

  space-after-colon:
    - 1
    - include: true

  space-after-comma:
    - 1
    - include: true

  space-around-operator:
    - 1
    - include: true

  space-before-bang:
    - 1
    - include: false

  space-before-brace:
    - 1
    - include: true

  space-before-colon:
    - 1
    - include: false

  space-between-parens:
    - 1
    - include: false

  trailing-semicolon:
    - 1
    - include: true

  url-quotes:
    - 1

  variable-for-property:
    - 0
    - properties: []

  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: camelcase

  zero-unit:
    - 1
    - include: false
