# Website settings
title: zombination
description: we are zombies
baseurl: ''
url: https://zombination.net
permalink: /:title
timezone: Asia/Seoul
version: 0.0.1

# Exclude files from the production build
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CNAME

# Google sitemap generation
gems:
- jekyll-sitemap

# Markdown settings
markdown: kramdown

# Code highlighter settings
highlighter: pygments

# Sass settings
# http://sass-lang.com/
# http://jekyllrb.com/docs/assets/#sassscss
sass:
  add_charset: true
  sass_dir: assets/styles/_scss
  style: compressed
