# Website settings
title: zombination
description: we are zombies
baseurl: ''
url: https://zombination.net
permalink: /:title
timezone: Asia/Seoul
version: 0.0.1

# Language and locale settings
language:
  code: ko
  locale: ko_KR
  name: Korean

# Exclude files from the production build
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CNAME

# Google sitemap generation
gems:
- jekyll-sitemap

# Markdown settings
markdown: kramdown

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false

# Code highlighter settings
highlighter: rouge

# Sass settings
# http://sass-lang.com/
# http://jekyllrb.com/docs/assets/#sassscss
sass:
  add_charset: true
  sass_dir: assets/styles/_scss
  style: compressed

# Compress HTML
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
